### ISSUE TITLE
BlockingIOError: [Errno 11] write could not complete without blocking

### ISSUE THREAD

**Issue by draeician** [tonder0812/gogoanime#5]
Traceback (most recent call last):
  File "/home/draeician/git/gogoanime/printer/printer.py", line 76, in render
  File "/home/draeician/git/gogoanime/printer/printer.py", line 112, in __render
  File "/home/draeician/git/gogoanime/printer/console/linux_console.py", line 1176, in set_text
BlockingIOError: [Errno 11] write could not complete without blocking

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
  File "/usr/lib/python3.12/threading.py", line 1012, in run
  File "/home/draeician/git/gogoanime/printer/printer.py", line 82, in render
  File "/home/draeician/git/gogoanime/utils/debugging.py", line 6, in debug_log
OSError: [Errno 24] Too many open files: 'debug.log'

**Comment by draeician** [comment]
Issue comes up with large series, for example boruto-naruto-next-generations-dub has over 200 episodes.

**Comment by tonder0812** [comment]
Should be fixed by 2fe88fbfc10f0fc0119920f1626e3bc0baf9c652
