### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by draeician** [tonder0812/gogoanime#6]
Check failed:
[Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/draeician/git/gogoanime/check.py", line 114, in main
  File "/home/draeician/git/gogoanime/saving.py", line 63, in f
  File "/home/draeician/git/gogoanime/check.py", line 63, in check
  File "/home/draeician/git/gogoanime/downloader.py", line 194, in download_anime
  File "/home/draeician/git/gogoanime/downloader.py", line 119, in download_episode
  File "/home/draeician/git/gogoanime/venv/lib/python3.12/site-packages/httpx/_client.py", line 1397, in __init__
  File "/home/draeician/git/gogoanime/venv/lib/python3.12/site-packages/httpx/_client.py", line 1445, in _init_transport
  File "/home/draeician/git/gogoanime/venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 272, in __init__
  File "/home/draeician/git/gogoanime/venv/lib/python3.12/site-packages/httpx/_config.py", line 52, in create_ssl_context
  File "/home/draeician/git/gogoanime/venv/lib/python3.12/site-packages/httpx/_config.py", line 76, in __init__
  File "/home/draeician/git/gogoanime/venv/lib/python3.12/site-packages/httpx/_config.py", line 88, in load_ssl_context
  File "/home/draeician/git/gogoanime/venv/lib/python3.12/site-packages/httpx/_config.py", line 147, in load_ssl_context_verify
OSError: [Errno 24] Too many open files

**Comment by draeician** [comment]
Issue comes up with large series, for example boruto-naruto-next-generations-dub has over 200 episodes.

**Comment by tonder0812** [comment]
Should be fixed by df204d4e3b76198b3a37201d0e26ca204987b7c6
